//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinhVien", Namespace="http://schemas.datacontract.org/2004/07/TungQLSV")]
    [System.SerializableAttribute()]
    public partial class SinhVien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DiemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaSVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSVField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Diem {
            get {
                return this.DiemField;
            }
            set {
                if ((this.DiemField.Equals(value) != true)) {
                    this.DiemField = value;
                    this.RaisePropertyChanged("Diem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lop {
            get {
                return this.LopField;
            }
            set {
                if ((object.ReferenceEquals(this.LopField, value) != true)) {
                    this.LopField = value;
                    this.RaisePropertyChanged("Lop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaSV {
            get {
                return this.MaSVField;
            }
            set {
                if ((object.ReferenceEquals(this.MaSVField, value) != true)) {
                    this.MaSVField = value;
                    this.RaisePropertyChanged("MaSV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenSV {
            get {
                return this.TenSVField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSVField, value) != true)) {
                    this.TenSVField = value;
                    this.RaisePropertyChanged("TenSV");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemSinhVien", ReplyAction="http://tempuri.org/IService1/ThemSinhVienResponse")]
        void ThemSinhVien(WindowsFormsApp1.ServiceReference1.SinhVien sv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemSinhVien", ReplyAction="http://tempuri.org/IService1/ThemSinhVienResponse")]
        System.Threading.Tasks.Task ThemSinhVienAsync(WindowsFormsApp1.ServiceReference1.SinhVien sv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuaSinhVien", ReplyAction="http://tempuri.org/IService1/SuaSinhVienResponse")]
        void SuaSinhVien(WindowsFormsApp1.ServiceReference1.SinhVien sv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuaSinhVien", ReplyAction="http://tempuri.org/IService1/SuaSinhVienResponse")]
        System.Threading.Tasks.Task SuaSinhVienAsync(WindowsFormsApp1.ServiceReference1.SinhVien sv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaSinhVien", ReplyAction="http://tempuri.org/IService1/XoaSinhVienResponse")]
        void XoaSinhVien(string maSV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaSinhVien", ReplyAction="http://tempuri.org/IService1/XoaSinhVienResponse")]
        System.Threading.Tasks.Task XoaSinhVienAsync(string maSV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachSinhVien", ReplyAction="http://tempuri.org/IService1/LayDanhSachSinhVienResponse")]
        WindowsFormsApp1.ServiceReference1.SinhVien[] LayDanhSachSinhVien();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachSinhVien", ReplyAction="http://tempuri.org/IService1/LayDanhSachSinhVienResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.SinhVien[]> LayDanhSachSinhVienAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.IService1>, WindowsFormsApp1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ThemSinhVien(WindowsFormsApp1.ServiceReference1.SinhVien sv) {
            base.Channel.ThemSinhVien(sv);
        }
        
        public System.Threading.Tasks.Task ThemSinhVienAsync(WindowsFormsApp1.ServiceReference1.SinhVien sv) {
            return base.Channel.ThemSinhVienAsync(sv);
        }
        
        public void SuaSinhVien(WindowsFormsApp1.ServiceReference1.SinhVien sv) {
            base.Channel.SuaSinhVien(sv);
        }
        
        public System.Threading.Tasks.Task SuaSinhVienAsync(WindowsFormsApp1.ServiceReference1.SinhVien sv) {
            return base.Channel.SuaSinhVienAsync(sv);
        }
        
        public void XoaSinhVien(string maSV) {
            base.Channel.XoaSinhVien(maSV);
        }
        
        public System.Threading.Tasks.Task XoaSinhVienAsync(string maSV) {
            return base.Channel.XoaSinhVienAsync(maSV);
        }
        
        public WindowsFormsApp1.ServiceReference1.SinhVien[] LayDanhSachSinhVien() {
            return base.Channel.LayDanhSachSinhVien();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.SinhVien[]> LayDanhSachSinhVienAsync() {
            return base.Channel.LayDanhSachSinhVienAsync();
        }
    }
}
